#!/usr/bin/env python3

import click
from operations.Builder import build


@click.group()
def cli():
    pass


def main():
    cli.add_command(build, name="build")
    cli()

if __name__ == "__main__":
    main()