#!/usr/bin/env python3
import sys, os

pypath = "/usr/local/lib/kubevar/bin/python3"

devmode = False
if "KUBEVAR_ENV" in os.environ and os.environ["KUBEVAR_ENV"].lower() in ["dev", "development"]:
    devmode=True

if sys.executable != pypath and not devmode:
    import subprocess
    subprocess.call([pypath, *sys.argv])
else:
    from kubevarpkg import main
    main()